version: "3.8"

services:
  db:
    image: postgres:13
    container_name: odoo-db-prod
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo-brasil-custom:latest  # <- Nome da sua imagem final
    container_name: odoo-web-prod
    restart: always
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-data-prod:/var/lib/odoo
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data_prod:
  odoo-data-prod:
